flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- QuickCheck-2.8.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.0
- binary-0.8.4.0
- bytestring-0.10.6.0
- clock-0.7.2
- directory-1.2.6.3
- logict-0.6.0.2
- mtl-2.2.1
- optparse-applicative-0.12.1.0
- parsec-3.1.11
- primitive-0.6.1.0
- process-1.4.2.0
- random-1.1
- regex-base-0.93.2
- regex-tdfa-1.2.2
- smallcheck-1.1.1
- stm-2.4.4.1
- tagged-0.8.4
- tasty-0.11.0.3
- tasty-hunit-0.9.2
- tasty-quickcheck-0.8.4
- tasty-smallcheck-0.8.1
- text-1.2.2.1
- tf-random-0.5
- transformers-compat-0.5.1.4
- unbounded-delays-0.1.0.9
- unix-2.7.2.0
resolver: ghc-8.0.1
